[package]
name = "hot-reload-keygen"
author = "SUP2Ak"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"