name: Build UI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'crates/hot-reload-ui/**'
      - '.github/workflows/build-ui.yml'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permet de lancer manuellement

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: hot-reload-ui.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: hot-reload-ui
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: hot-reload-ui

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Build
      run: cargo build --release --target ${{ matrix.target }} -p hot-reload-ui
      
    - name: Create Release Folder
      run: mkdir release

    - name: Package Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../release/hot-reload-ui_${{ matrix.target }}.zip ${{ matrix.binary }}

    - name: Package Unix
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        zip ../../../release/hot-reload-ui_${{ matrix.target }}.zip ${{ matrix.binary }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hot-reload-ui_${{ matrix.target }}
        path: release/*.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          hot-reload-ui_*/hot-reload-ui_*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}