name: yarn Build Check

on:
  push:
    branches: [ "main" ]
    paths:
      - 'resources/hot-reload/**'
      - '.github/workflows/yarn.yml'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install yarn
      run: npm install -g yarn@1.22.22

    - name: Get yarn store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(yarn store path --silent)" >> $GITHUB_ENV

    - name: Cache yarn modules
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-store-

    - name: Install dependencies
      run: |
        cd resources/hot-reload
        yarn install

    - name: Build
      run: |
        cd resources/hot-reload
        yarn build

    - name: Check build output
      run: |
        cd resources/hot-reload
        if [ ! -f "dist/server.js" ]; then
          echo "Build failed: server.js not found"
          exit 1
        fi